In [21]:
import numpy as np
mang = np.array([1,2,3,6,2,31])
print(mang)
element = mang[5]
print(element)

[ 1  2  3  6  2 31]
31


In [22]:

mang2chieu = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Mang 2 chieu:")
print(mang2chieu)


element = mang2chieu [1, 2]
print(element)

Mang 2 chieu:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [23]:
mangt = np.zeros(5)
print(mang)

mang = np.ones(5)
print(mang)

mang = np.empty(5)
print(mang)

mang = np.arange(100)
print(mang)

mang = np.linspace(0, 10, num=7)
print(mang)

mang = np.ones(5, dtype=np.int64)
mang

[ 1  2  3  6  2 31]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


array([1, 1, 1, 1, 1], dtype=int64)

In [24]:

mang1 = np.array([3, 1, 2, 4, 5,2,21,412,112])
print(mang1)


mang1 = np.sort(mang1)
print(mang1)


mang1 = np.sort(mang1)[::-1]
print(mang1)


mang1 = np.append(mang1, 100)
print(mang1)

mang1 = np.delete(mang1, 3)
print(mang1)

[  3   1   2   4   5   2  21 412 112]
[  1   2   2   3   4   5  21 112 412]
[412 112  21   5   4   3   2   2   1]
[412 112  21   5   4   3   2   2   1 100]
[412 112  21   4   3   2   2   1 100]


In [25]:
mang = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

hang = np.sort(mang, axis=1) # tăng dần
print(hang)
cot = np.sort(mang, axis=0) # tăng dần
print(cot)

[[1 2 3]
 [4 6 8]
 [5 7 9]]
[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [26]:

mang = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

hang = -np.sort(-mang, axis=1) # giảm dần
print(hang)

cot = -np.sort(-mang, axis=0) # giảm dần
print(cot)

[[3 2 1]
 [8 6 4]
 [9 7 5]]
[[9 7 8]
 [4 6 5]
 [3 1 2]]


In [27]:
mang = np.array([[1, 2, 3], [4, 5, 6]])

chieu = mang.ndim  
sz = mang.size  
hdang = mang.shape  
print("Số chiều:", chieu)
print("Kích thước:", sz)
print("Hình dạng:", hdang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [28]:
mang = np.array([1, 2, 3, 4, 5])
mang_doi = mang.astype(float)
print(mang_doi)

[1. 2. 3. 4. 5.]


In [29]:
mang = np.array([1, 2, 3, 4, 5, 6])
doi1 = mang.reshape(2,3)
print(doi1)
doi2 = mang.reshape(3,2)
print(doi2)

doi3 = mang.flatten()
print(doi3)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [30]:

mang = np.array([1, 2, 3, 4, 5])

cat1 = mang[1:4]  
print(cat1)

cat2 = mang[:-1]  
print(cat2)

cat3 = mang[-2:]  
print(cat3)

[2 3 4]
[1 2 3 4]
[4 5]


In [31]:

mang = np.array([[1, 2, 3], [4, 5, 6]])
print(mang)
chuyenvi = mang.T
print(chuyenvi)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [32]:
m1 = np.array([1, 2, 3])
m2 = np.array([4, 5, 6])
m = np.concatenate((m1, m2))
print(m)

[1 2 3 4 5 6]


In [39]:

m = np.array([1, 2, 3, 4, 5,6 ,7 ,8 ,9, 22,131])
tong = np.sum(m)
print("Tổng của mảng :", tong)

trungbinh = np.mean(m)
print("Giá trị trung bình của mảng :", trungbinh)

max = np.max(m)
min = np.min(m)
print("Giá trị lớn nhất trong mảng arr:", max)
print("Giá trị nhỏ nhất trong mảng arr:", min)

dolech = np.std(m)
print("Độ lệch chuẩn của mảng arr:", dolech)


phuongsai = np.var(m)
print("Phương sai của mảng m:", phuongsai)


m1 = np.array([5, 10, 3])
m2 = np.array([4, 6, 9])
tichchap = np.dot(m1, m2)
print("Tổng tích chập của m1 và m2:", tichchap)

Tổng của mảng : 198
Giá trị trung bình của mảng : 18.0
Giá trị lớn nhất trong mảng arr: 131
Giá trị nhỏ nhất trong mảng arr: 1
Độ lệch chuẩn của mảng arr: 36.138621999185304
Phương sai của mảng m: 1306.0
Tổng tích chập của m1 và m2: 107
